"""Git Auto-Commit - Safe automatic git operations for SynapseScanner v1.4.0"""
import os
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Optional, List


class GitAutoCommit:
    """
    Handles automatic git operations for documentation updates.
    Implements safety checks to prevent destructive operations.
    """
    
    def __init__(self, repo_path: Optional[str] = None):
        """Initialize with repository path."""
        self.repo_path = Path(repo_path) if repo_path else Path.cwd()
        self._git_available = None
    
    def is_git_available(self) -> bool:
        """Check if git is available on system."""
        if self._git_available is not None:
            return self._git_available
        
        try:
            result = subprocess.run(
                ["git", "--version"],
                capture_output=True,
                check=True
            )
            self._git_available = True
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            self._git_available = False
            return False
    
    def is_git_repo(self) -> bool:
        """Check if current directory is a git repository."""
        if not self.is_git_available():
            return False
        
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "rev-parse", "--git-dir"],
                capture_output=True,
                check=True
            )
            return True
        except subprocess.CalledProcessError:
            return False
    
    def has_uncommitted_changes(self) -> bool:
        """Check if there are uncommitted changes."""
        if not self.is_git_repo():
            return False
        
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "status", "--porcelain"],
                capture_output=True,
                text=True,
                check=True
            )
            return bool(result.stdout.strip())
        except subprocess.CalledProcessError:
            return False
    
    def should_auto_commit(self, force: bool = False) -> bool:
        """
        Check if auto-commit should proceed.
        
        Args:
            force: Bypass safety checks if True
            
        Returns:
            True if auto-commit should proceed
        """
        if not self.is_git_available():
            print("[!] Git not available on system")
            return False
        
        if not self.is_git_repo():
            print("[!] Not a git repository")
            return False
        
        if self.has_uncommitted_changes() and not force:
            print("[!] Uncommitted changes detected. Use --force to bypass.")
            print("[!] Stash or commit existing changes first.")
            return False
        
        return True
    
    def stage_files(self, files: List[str]) -> bool:
        """Stage files for commit."""
        if not files:
            return True
        
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "add"] + files,
                capture_output=True,
                text=True,
                check=True
            )
            print(f"[OK] Staged {len(files)} file(s)")
            return True
        except subprocess.CalledProcessError as e:
            print(f"[!] Failed to stage files: {e.stderr}")
            return False
    
    def commit_breakthrough(self, files: List[str], pattern_name: str) -> bool:
        """
        Commit breakthrough documentation.
        
        Args:
            files: List of files to commit
            pattern_name: Name of the breakthrough pattern
            
        Returns:
            True if commit successful
        """
        if not self.stage_files(files):
            return False
        
        # Generate commit message
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        short_name = pattern_name[:50] if len(pattern_name) <= 50 else pattern_name[:47] + "..."
        
        message = f"""docs(breakthrough): {short_name}

- Discovered: {timestamp}
- Auto-generated by SynapseScanner v1.4.0

This breakthrough was automatically documented during a research scan.
"""
        
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "commit", "-m", message],
                capture_output=True,
                text=True,
                check=True
            )
            print(f"[OK] Committed breakthrough documentation")
            print(f"[OK] Message: docs(breakthrough): {short_name}")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"[!] Failed to commit: {e.stderr}")
            return False
    
    def push_changes(self, force: bool = False) -> bool:
        """
        Push changes to origin.
        
        Args:
            force: Force push (use with caution)
            
        Returns:
            True if push successful
        """
        try:
            cmd = ["git", "-C", str(self.repo_path), "push", "origin"]
            if force:
                cmd.append("--force")
            
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True
            )
            print(f"[OK] Pushed to origin")
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"[!] Failed to push: {e.stderr}")
            print("[*] You can push manually with: git push origin main")
            return False
    
    def get_last_commit_message(self) -> Optional[str]:
        """Get the last commit message."""
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "log", "-1", "--pretty=%B"],
                capture_output=True,
                text=True,
                check=True
            )
            return result.stdout.strip()
        except subprocess.CalledProcessError:
            return None
    
    def is_breakthrough_commit(self, message: Optional[str] = None) -> bool:
        """Check if last commit was an auto-generated breakthrough."""
        if message is None:
            message = self.get_last_commit_message()
        
        if not message:
            return False
        
        return (
            message.startswith("docs(breakthrough):") or
            "Auto-generated by SynapseScanner" in message
        )
    
    def check_remote(self) -> bool:
        """Check if remote origin is configured."""
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo_path), "remote", "get-url", "origin"],
                capture_output=True,
                text=True,
                check=True
            )
            return bool(result.stdout.strip())
        except subprocess.CalledProcessError:
            return False
    
    def get_status(self) -> dict:
        """Get comprehensive git status."""
        status = {
            "is_git_repo": self.is_git_repo(),
            "has_uncommitted_changes": self.has_uncommitted_changes(),
            "has_remote": self.check_remote(),
            "can_auto_commit": self.should_auto_commit(),
        }
        
        if status["is_git_repo"]:
            status["last_commit"] = self.get_last_commit_message()[:50]
            status["is_last_auto"] = self.is_breakthrough_commit()
        
        return status
    
    def print_status(self):
        """Print git status to terminal."""
        status = self.get_status()
        
        print("\n  Git Status:")
        print(f"    Repository: {'✓' if status['is_git_repo'] else '✗'}")
        print(f"    Clean working tree: {'✓' if not status['has_uncommitted_changes'] else '✗'}")
        print(f"    Remote configured: {'✓' if status['has_remote'] else '✗'}")
        print(f"    Ready for auto-commit: {'✓' if status['can_auto_commit'] else '✗'}")
        
        if status.get("last_commit"):
            print(f"    Last commit: {status['last_commit']}...")
